import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Shorten your URLs quickly and easily" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 flex flex-col items-center justify-center p-4">
        <header className="text-white text-4xl font-bold mb-8">
          Welcome to URL Shortener
        </header>
        <main className="bg-white p-8 rounded-lg shadow-lg w-full max-w-md">
          <h1 className="text-2xl font-semibold mb-4 text-gray-600">Shorten your URL</h1>
          <form className="flex flex-col gap-4">
            <input
              type="url"
              placeholder="Enter your URL"
              className="p-2 border border-gray-300 text-gray-600 rounded"
              required
            />
            <button
              type="submit"
              className="bg-blue-500 text-white p-2 rounded hover:bg-blue-600 transition"
            >
              Shorten
            </button>
          </form>
        </main>
        <footer className="text-white mt-8 text-center">
          <p>&copy; 2024 EncurtaURL. All rights reserved
            <br />Layout generated by gpt4o</p>
        </footer>
      </div>
    </>
  );
}